<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Bpmn2UseCase" nsURI="platform:/plugin/Bpmn2UseCase/model/Bpmn2UseCase.ecore" nsPrefix="Bpmn2UseCase">
  <eClassifiers xsi:type="ecore:EClass" name="P2UC">
    <eSuperTypes href="platform:/plugin/TGGRuntime/model/TGGRuntime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/SimpleBPMN/model/SimpleBPMN.ecore#//Process"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/SimpleUseCase/model/SimpleUseCase.ecore#//UseCase"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FN2F">
    <eSuperTypes href="platform:/plugin/TGGRuntime/model/TGGRuntime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/SimpleBPMN/model/SimpleBPMN.ecore#//FlowNode"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/SimpleUseCase/model/SimpleUseCase.ecore#//Flow"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GW2S">
    <eSuperTypes href="platform:/plugin/TGGRuntime/model/TGGRuntime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/SimpleBPMN/model/SimpleBPMN.ecore#//Gateway"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/SimpleUseCase/model/SimpleUseCase.ecore#//Step"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FN2S">
    <eSuperTypes href="platform:/plugin/TGGRuntime/model/TGGRuntime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/SimpleBPMN/model/SimpleBPMN.ecore#//FlowNode"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/SimpleUseCase/model/SimpleUseCase.ecore#//Step"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eSubpackages name="Rules" nsURI="platform:/plugin/Bpmn2UseCase/model/Bpmn2UseCase.ecore#//Rules" nsPrefix="Rules">
    <eClassifiers xsi:type="ecore:EClass" name="Process2UseCase">
      <eSuperTypes href="platform:/plugin/TGGRuntime/model/TGGRuntime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Task2NormalStep" abstract="true">
      <eSuperTypes href="platform:/plugin/TGGRuntime/model/TGGRuntime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PG2ParallelStep" abstract="true">
      <eSuperTypes href="platform:/plugin/TGGRuntime/model/TGGRuntime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PG2ParallelStepAfterPG">
      <eSuperTypes href="platform:/plugin/TGGRuntime/model/TGGRuntime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Task2NormalStepSeq">
      <eSuperTypes href="platform:/plugin/TGGRuntime/model/TGGRuntime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Task2NormalStepFirst">
      <eSuperTypes href="platform:/plugin/TGGRuntime/model/TGGRuntime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PG2ParallelStepSeq">
      <eSuperTypes href="platform:/plugin/TGGRuntime/model/TGGRuntime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PG2ParallelStepFirst">
      <eSuperTypes href="platform:/plugin/TGGRuntime/model/TGGRuntime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EndEvent2FinalStateFirst">
      <eSuperTypes href="platform:/plugin/TGGRuntime/model/TGGRuntime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Task2NormalStepAfterPG">
      <eSuperTypes href="platform:/plugin/TGGRuntime/model/TGGRuntime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EndEvent2FinalState" abstract="true">
      <eSuperTypes href="platform:/plugin/TGGRuntime/model/TGGRuntime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EndEvent2FinalStateSeq">
      <eSuperTypes href="platform:/plugin/TGGRuntime/model/TGGRuntime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LastStepInFlow" abstract="true">
      <eSuperTypes href="platform:/plugin/TGGRuntime/model/TGGRuntime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LastStepInPFlow">
      <eSuperTypes href="platform:/plugin/TGGRuntime/model/TGGRuntime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EG2Choice" abstract="true">
      <eSuperTypes href="platform:/plugin/TGGRuntime/model/TGGRuntime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EG2ChoiceSeq">
      <eSuperTypes href="platform:/plugin/TGGRuntime/model/TGGRuntime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EG2ChoiceFirst">
      <eSuperTypes href="platform:/plugin/TGGRuntime/model/TGGRuntime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EG2ChoiceAfterPG">
      <eSuperTypes href="platform:/plugin/TGGRuntime/model/TGGRuntime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Task2NormalStepAfterDefEG">
      <eSuperTypes href="platform:/plugin/TGGRuntime/model/TGGRuntime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Task2NormalStepAfterEG">
      <eSuperTypes href="platform:/plugin/TGGRuntime/model/TGGRuntime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Class1">
      <eSuperTypes href="platform:/plugin/TGGRuntime/model/TGGRuntime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LastStepInAltFlow">
      <eSuperTypes href="platform:/plugin/TGGRuntime/model/TGGRuntime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PG2ParallelStepAfterDefEG">
      <eSuperTypes href="platform:/plugin/TGGRuntime/model/TGGRuntime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PG2ParallelStepAfterEG">
      <eSuperTypes href="platform:/plugin/TGGRuntime/model/TGGRuntime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EG2ChoiceStepAfterDefEG">
      <eSuperTypes href="platform:/plugin/TGGRuntime/model/TGGRuntime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EG2ChoiceStepAfterEG">
      <eSuperTypes href="platform:/plugin/TGGRuntime/model/TGGRuntime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EndEvent2FinalStateGWSeq">
      <eSuperTypes href="platform:/plugin/TGGRuntime/model/TGGRuntime.ecore#//AbstractRule"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
